faverest/config/routes.rb
Rails.application.routes.draw do

devise_for :users
resources :favs do
    member do
    put "Like", to: "favs#upvote"
  end
end

root "favs#index"
end

faverest/app/models/fav.rb
class Fav < ActiveRecord::Base
  acts_as_votable
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

faverest/app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :favs
end

faverest/app/controllers/favs_controller.rb
class FavsController < ApplicationController
  before_action :find_fav, only: [:show, :edit, :update, :destroy, :upvote]

  def index
    @favs = Fav.all.order("created_at DESC")
  end

  def show
  end

  def new
    @fav = current_user.favs.build
  end

  def create
    @fav = current_user.favs.build(fav_params)
    if @fav.save
      redirect_to @fav, notice: "Successfully created new fav"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @fav.update(fav_params)
      redirect_to @fav, notice: "Fav was Successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @fav.destroy
    redirect_to root_path
  end

  def upvote
    @fav.upvote_by current_user
    redirect_to :back
  end

  private

  def fav_params
    params.require(:fav).permit(:title, :description, :image)
  end

  def find_fav
    @fav = Fav.find(params[:id])
  end

end

faverest/app/helpers/favs_helper.rb
module FavsHelper
end

faverest/app/views/favs/_form.html.erb
<%= simple_form_for @fav, html:{multipart: true } do |f| %>

  <%= f.input :title, input_html: { class: 'form-control'} %>
  <%= f.input :description %>
  <%= f.input :image, input_html: { class: 'form-control'} %>

  <%= f.button :submit %>

<% end %>

faverest/app/views/favs/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div id="edit_page" class="current_image">
    <h1>Edit Fav</h1>
    <%= image_tag @fav.image.url(:medium) %>
    <%= render 'form' %>
    <%= link_to 'Cancel', fav_path %>
  </div>
</div>

faverest/app/views/favs/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Faverest</title>
  </head>
  <body>
    <header class="heading">
      <div class="container">
        <div class="jumbotron">
          <h1>Welcome To Faverest</h1>
          <h2><strong>Find all your favorite interest in one place!</strong></h2>
        </div>
    </header>
    <main>

    <div class="nomargin row">
      <div class="col-border col-lg-1">Food and Drink</div>
      <div class="col-border col-lg-1">Hair and Beauty</div>
      <div class="col-border col-lg-1">Home Decor</div>
      <div class="col-border col-lg-1">Photography</div>
      <div class="col-border col-lg-1">Sports</div>
      <div class="col-border col-lg-1">Technology</div>
      <div class="col-border col-lg-1">Men's Fashion</div>
      <div class="col-border col-lg-1">Women's Fashion</div>
      <div class="col-border col-lg-1">Travel</div>
      <div class="col-border col-lg-1">Weddings</div>
      <div class="col-border col-lg-1">Science</div>
      <div class="col-border col-lg-1">Entertainment</div>
      <div class="col-border col-lg-1">Nature</div>
      <div class="col-border col-lg-1">Cars and Bicycles</div>
    </div>

  <div id="favs" transitions-enabled>
    <% @favs.each do |fav| %>
      <div class="box panel panel-default">
        <br>
      <%= link_to (image_tag fav.image.url(:medium)), fav %>
    <div class="panel-body">
        <h2> <%= link_to fav.title, fav %> </h2>
        <p>
          <div class="user">
            Submitted by
            <%= fav.user.email %>
          </div>
        </p>
    </div>
    </div>
    <% end %>
</div>

    </main>

<footer>
  <div class="main">
      <p>Copyright 2009 Your name</p>
  </div>
</footer>
  <!-- <div class="form-page" style="height:780px;" data-reactid=".0.4.$/.0.4"><div class="background-image-component" style="background-color:#eee;width:1277px;height:780px;" data-reactid=".0.4.$/.0.4.0"><div class="image-container" style="-webkit-transition-property: -webkit-transform; transition-property: -webkit-transform; -webkit-transition-duration: 0.6s; transition-duration: 0.6s; opacity: 1;" data-reactid=".0.4.$/.0.4.0.0"><img class="background-image" src="" style="width:1348px;height:791px;top:-5px;left:-35px;-webkit-transition-property:-webkit-transform;-webkit-transition-duration:0.6s;" data-reactid=".0.4.$/.0.4.0.0.0"></div> -->
  </body>
</html>

faverest/app/views/favs/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>New Form</h1>
  <%= render 'form' %>
  <br>
  <%= button_to "Home page", root_path, method: :get %>

</div>

faverest/app/views/favs/show.html.erb
<div id="fav_show">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
        <div class="panel-heading">
          <h4><%= @fav.title %></h4>
        </div>
          <div class="panel-body" id="fav_image">
            <%= image_tag @fav.image.url%>
          </div>

      <p><div cla ss="description"><%= @fav.description %></div></p>

      <div class="user">
        <p>Submitted by <%= @fav.user.email %></p>
      </div>

    <div class="panel-footer">
        <div class="row">
          <div class="col-md-6" class="btn-group">
            <% if user_signed_in? %>

            <div class="btn btn-default pull-right">
              <%= link_to 'Edit', edit_fav_path %>
            </div>

            <div class="btn btn-default pull-right">
              <%= link_to 'Delete', fav_path, method: :delete, data: { Confirm: "Are you sure?" }%>
            </div>

            <div class="btn btn-default pull-right">
              <%= link_to Like_fav_path (@fav), method: :put do %>
              <span class="glyphicon glyphicon-heart"><%= @fav.get_upvotes.size %></span>
                <% end %>
              <% end %>

            </div>
          </div>
      </div>
    </div>

</div>
</div>

faverest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Faverest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
   <div class="navbar-header">
      <div class="navbar-brand"><%= link_to "Faverest", root_path %></div>
   </div>
   <% if user_signed_in? %>
   <div>
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to "Home", root_path %></li>
         <li class="active"><%= link_to "New Fav", new_fav_path %></li>
         <li class="active"><%= link_to "My Favorites", root_path %></li>
         <li></li>
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               My Account
               <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <li><a href="#">Profile</a></li>
               <li><%= link_to " Edit Account", edit_user_registration_path %></li>
               <li><a href="#"></a></li>
               <li class="divider"></li>
               <li><a href="#"></a></li>
               <li class="divider"></li>
               <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
         </li>
         <% else %>
         <div>
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><%= link_to "Create an Account", new_user_registration_path %></li>
              <li class="active"><%= link_to "Login",  new_user_session_path %></li>
              <li class="active"><%= link_to "About Us", new_fav_path %></li>
              <li class="active"><%= link_to "Contact Us", root_path %></li>
             </ul>
          </div>
       <% end %>
      </ul>
   </div>
</nav>
  <h2 class="notice"><%= notice %></h2>
  <h2 class="alert"><%= alert %></h2>
<%= yield %>

</body>



</html>